config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts do 
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end 
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader


  def self.search(search)
    return Post.all unless search
    Post.where('title LIKE(?)', "%#{search}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miya.D-Life</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header__title">
        <%= link_to "Miya,Disney-Life", root_path, class: "header__title--text" %>
      </div>
      <div class="header__right">
      <% if user_signed_in? %>
          <%= link_to current_user.nickname, user_path(current_user), class: "header__right--btn" %>
          <%= link_to "New post", new_post_path, class: "header__right--btn" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "header__right--btn" %>
        <%= link_to "sign up", new_user_registration_path, class: "header__right--btn" %>
      <% end %>
      </div>
    </header>
      <div class="navbar">
      <p>PICK UP List</p>
        <p>
          <a href="https://www.tokyodisneyresort.jp/">Tokyo Disney Resort</a>
          <a href="https://store.disney.co.jp/">Disney Store</a>
          <a href="https://twitter.com/disneyjp?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor">Twitter</a>
          <a href="https://www.instagram.com/tokyodisneyresort_official/?hl=ja">Instagram</a>
        </p>
      </div>
      <div class="contents">
        <%= yield %>
      </div>
    <div class="footer">
    Wolt Disney
     All our dreams can come true, if we have the courage to pursue them. I only hope that we don’t lose sight of one thing – that it was all started by a mouse.
       
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, class: :form, local: true do |form| %>
<%= f.label :画像 %><br />
  <%= f.file_field :img, class: "image" %>
  <p><%= f.check_box :remove_img %>画像を削除する</p>
  <%= f.submit %>
<% end %>

app/views/posts/_post.html.erb
<div class="content">
  <div class="content__left">
    <div class="content__left--image"></div>
  </div>
  <div class="content__right">
    <div class="content__right__top">
      <%= link_to post.title, post_path(post.id), class: "content__right__top--title" %>
    </div>
    <div class="content__right__bottom">
      <div class="content__right__bottom--userName">
        <%= link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn" %>
      </div>
      <div class="content__right__bottom--date">
        <%= post.created_at %>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.html.erb
<h1>投稿が完了しました</h1>
<%= link_to 'トップページに戻る', '/posts' %>

app/views/posts/edit.html.erb
<div class="content__title">
  Edit Post
</div>
<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.file_field :image, placeholder: "Image Url" %>
  <%= form.text_area :content, placeholder: :本文, class: :form__text %>
  <%= form.submit "投稿", class: :form__btn %>
<% end %>

app/views/posts/index.html.erb
<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "Search", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @posts.each do |post| %>
    <%= render partial: "post", locals: { post: post } %>
  <% end %>
  <%= paginate(@posts) %>
</div>

app/views/posts/new.html.erb
<div class="content__title">
  New Post
</div>
  <div class="container">
    <%= form_with model: @post, class: :form, local: true do |form| %>
      <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
      <%= form.file_field :image, placeholder: "Image Url" %>
      <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
      <%= form.submit '投稿する', class: :form__btn %>
    <% end %>
  </div>

app/views/posts/search.html.erb
<% @posts.each do |post| %>
  <%= render partial: "post", locals: { post: post } %>
<% end %>

app/views/posts/show.html.erb
<div class="postTitle">
  <%= @post.title %>
</div>
<div class="postDate">
  <%= @post.created_at %>
</div>
<div class="postAuthor">
</div>
<% if user_signed_in? && current_user.id == @post.user_id %>
  <div class="postManage">
    <%= link_to "Modificare", edit_post_path(@post.id), class: "postManage__edit" %>
    <%= link_to "Elimina", post_path(@post.id), method: :delete, class: "postManage__delete" %>
  </div>
<% end %>
<div class="postText">
  <%= simple_format @post.content %>
</div>

  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@post, @comment], local: true) do |form| %>
        <%= form.text_area :content, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND"%>
      <% end %>
    <% else %>
      <strong><p>※※※ Posting comments requires new registration / login ※※※</p></strong>
    <% end %>

   <div class="comments">
      <h4>＜Comment List＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.content %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="postTitle">
  <%= @user.nickname %>さんの投稿一覧
</div>
<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "Search", class: "search-btn" %>
<% end %>
<% @posts.each do |post| %>
  <%= render partial: "posts/post", locals: { post: post } %>
<% end %>
<%= paginate(@posts) %>